services:
  redis:
    build:
      context: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - paylabs

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - paylabs

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:8080"
    depends_on:
      - backend
    networks:
      - paylabs

networks:
  paylabs:
    driver: bridge
