sonar.host.url=https://sonarcloud.io

# From your SonarCloud org/project
sonar.organization=khan8577
sonar.projectKey=khan8577_paylabs
sonar.projectName=paylabs

# Sources (your existing idea is correct)
sonar.sources=frontend/src,backend/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8
